print ("Napbshite v poradke vizrastaniya etapy razvitia cheloveka. Vsego 4 etapa")
print ("1")
a = input ()
print ("2")
b = input ()
print ("3")
c = input ()
print ("4")
d = input ()
print (a, b, c, d, sep = '=>')
